collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2658432
color:
  saturation: 0.7890549
  brandStrength: 0.5305864
  rhythmicContrast: 0.08515851
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.5357954
layout_spectrum: 0.6997852
name: Dunk
